# Generated by Django 5.2.6 on 2025-09-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0003_commentplace'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postfeature',
            unique_together=set(),
        ),
    ]
