# Generated by Django 5.2.6 on 2025-09-09 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_places', '0003_placefeature'),
        ('a_posts', '0004_alter_postfeature_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='a_places.place'),
        ),
        migrations.CreateModel(
            name='PostFeatureVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.SmallIntegerField(choices=[(1, 'Upvote'), (0, 'Neutral'), (-1, 'Downvote')], default=0)),
                ('post_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='a_posts.postfeature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post_feature', 'user')},
            },
        ),
    ]
