# Generated by Django 4.2.20 on 2025-09-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0005_alter_commentplace_place_postfeaturevote'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfeature',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='postfeature',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='postfeature',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.DeleteModel(
            name='PostFeatureVote',
        ),
    ]
