# Generated by Django 5.2.6 on 2025-09-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='business_category',
            field=models.CharField(default='bruh', max_length=200),
            preserve_default=False,
        ),
    ]
