# Generated by Django 5.2.6 on 2025-09-09 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_features', '0001_initial'),
        ('a_places', '0002_place_business_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_features.feature')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='a_places.place')),
            ],
            options={
                'unique_together': {('place', 'feature')},
            },
        ),
    ]
